### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by elric274** [cstamford/FasterLoadingTimes#1]
It would have been nice if u explained how did u reduce load times what does mod do?

**Comment by cstamford** [comment]
![fuckin-magnets-how-do-they-work-me-irl-2952337](https://github.com/user-attachments/assets/cf1bf924-ed23-4fa9-86a0-4cbf1a831491)

Serious answer: the code is right there, and there's even a detailed comment in the code explaining how it works.
